[project]
name = "cargo-registry"
authors = ["Alex Crichton <alex@alexcrichton.com>"]
version = "0.1.0"

[profile.release]
opt-level = 2

[lib]
name = "cargo_registry"
test = false
doctest = false

[[bin]]
name = "server"
test = false

[[bin]]
name = "migrate"
test = false

[[bin]]
name = "update-downloads"

[[bin]]
name = "delete-crate"
test = false

[[bin]]
name = "delete-version"
test = false

[[bin]]
name = "populate"
test = false

[[test]]
name = "all"
path = "src/tests/all.rs"

[dependencies]
s3 = { path = "src/s3" }
migrate = { path = "src/migrate" }
rand = "0.3"
time = "0.1"
git2 = "0.3"
flate2 = "0.2"
semver = "0.2"
url = "0.2.0"
postgres = { version = "0.10", features = ["time"] }
r2d2 = "0.6.0"
r2d2_postgres = "0.9"
openssl = "0.6"
curl = "0.2"
oauth2 = "0.1"
log = "0.3"
env_logger = "0.3"
rustc-serialize = "0.3"
license-exprs = "^1.1"

conduit = "0.7"
conduit-conditional-get = "0.7"
conduit-cookie = "0.7"
conduit-json-parser = "0.7"
conduit-log-requests = "0.7"
conduit-middleware = "0.7"
conduit-router = "0.7"
conduit-static = "0.7"
conduit-git-http-backend = "0.7"
civet = "0.8"
yaqb = { path = "/Users/sean/Documents/Projects/open-source/yaqb" }


[dev-dependencies]
conduit-test = "0.7"
bufstream = "0.1"

[features]
unstable = []
